# Generated by Django 4.2.7 on 2025-06-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_busquedagoogle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusquedaGoogle',
        ),
    ]
