# Generated by Django 4.2.7 on 2025-05-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopersonal',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='color',
            field=models.CharField(default='#70C1B3', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
