# Generated by Django 4.2.7 on 2025-05-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_eventopersonal_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FF3430', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='color',
            field=models.CharField(default='#FFE57C', max_length=7),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='eventopersonal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendario.categoriaevento'),
        ),
    ]
