# Generated by Django 4.2.7 on 2025-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_categoriaevento_alter_eventopersonal_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaevento',
            name='color',
            field=models.CharField(default='#FF7530', max_length=7),
        ),
    ]
