# Generated by Django 4.2.7 on 2025-06-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_eventoplantilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventopersonal',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='color',
            field=models.CharField(default='#FFB700', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventoplantilla',
            name='color',
            field=models.CharField(default='#6c63ff', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoplantilla',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CategoriaEvento',
        ),
    ]
