# Generated by Django 5.2.1 on 2025-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_remove_eventopersonal_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguidoresHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('seguidores', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('instagram_id', 'fecha')},
            },
        ),
    ]
