# Generated by Django 5.2.1 on 2025-07-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0007_seguidoreshistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventopersonal',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
