# Generated by Django 5.2.1 on 2025-05-23 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_adjunto_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='puede_marcar_como_completada',
            field=models.ManyToManyField(blank=True, related_name='puede_marcar_como_completada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='ultima_fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
