# Generated by Django 4.2.7 on 2025-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_tarea_completada_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='tarea.etiqueta'),
        ),
    ]
