# Generated by Django 5.2.1 on 2025-07-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0006_etiqueta_tarea_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Historia', 'Historia'), ('Publicacion', 'Publicacion'), ('Reel', 'Reel')], max_length=30),
        ),
    ]
