# Generated by Django 5.2.1 on 2025-07-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0007_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('historia', 'Historia'), ('publicacion', 'Publicacion'), ('reel', 'Reel')], max_length=30),
        ),
    ]
